# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cee5c82647ae31fe971406f4f782304360a665a01d0bc56b4f72f61b953d796d9cb366b2da2b18cec52a1ca6378d1001810e038dd36e6823879b3dd6f6b1f487

test:
  secret_key_base: 2df24859604864fcd14e5441adb4e4fee7646763a93d184047de754e8d57f7bee802ac2d84dcaf42619e0fcf1aca1671935144f8c78bf08b251d5226da67429f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
